# Generated by Django 4.2 on 2024-04-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
